
#!/usr/bin/env python3
"""
AQARION Object–Operator Contract semantic suite.

Purpose:
    executable guards against object/convention drift.

This suite does NOT prove AQARION theorems.

It checks only the frozen object semantics:

    K_T[x,T(x)] = 1
    K_T f = f o T
    T_* is equivalence-generated from image identifications
    raw image-block families are not silently treated as partitions
    one-step transport is distinct from raw image transport

Evidence class:
    VERIFIED COMPUTATION [V]

No NumPy.
No floating-point arithmetic.
No external repository.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable


@dataclass(frozen=True)
class Partition:
    blocks: tuple[frozenset[int], ...]

    def __post_init__(self) -> None:
        if not self.blocks:
            raise ValueError("partition must contain at least one block")

        flat = set()
        for block in self.blocks:
            if not block:
                raise ValueError("partition blocks must be nonempty")
            if flat.intersection(block):
                raise ValueError("partition blocks must be disjoint")
            flat.update(block)

    @property
    def elements(self) -> frozenset[int]:
        result: set[int] = set()
        for block in self.blocks:
            result.update(block)
        return frozenset(result)


def koopman_matrix(T: tuple[int, ...]) -> tuple[tuple[int, ...], ...]:
    """
    Frozen AQARION convention:

        K_T[x,y] = 1 iff y = T(x).
    """
    n = len(T)
    matrix = []

    for x in range(n):
        row = [0] * n
        row[T[x]] = 1
        matrix.append(tuple(row))

    return tuple(matrix)


def matrix_apply(
    matrix: tuple[tuple[int, ...], ...],
    values: tuple[int, ...],
) -> tuple[int, ...]:
    return tuple(
        sum(matrix[x][y] * values[y] for y in range(len(values)))
        for x in range(len(matrix))
    )


def find(parent: list[int], x: int) -> int:
    while parent[x] != x:
        parent[x] = parent[parent[x]]
        x = parent[x]
    return x


def union(parent: list[int], a: int, b: int) -> None:
    ra = find(parent, a)
    rb = find(parent, b)

    if ra != rb:
        parent[rb] = ra


def equivalence_classes(
    n: int,
    pairs: Iterable[tuple[int, int]],
) -> tuple[frozenset[int], ...]:
    parent = list(range(n))

    for a, b in pairs:
        union(parent, a, b)

    classes: dict[int, set[int]] = {}

    for x in range(n):
        root = find(parent, x)
        classes.setdefault(root, set()).add(x)

    return tuple(
        sorted(
            (frozenset(values) for values in classes.values()),
            key=lambda block: (min(block), len(block)),
        )
    )


def canonical_partition(
    blocks: Iterable[Iterable[int]],
) -> tuple[frozenset[int], ...]:
    return tuple(
        sorted(
            (frozenset(block) for block in blocks),
            key=lambda block: (min(block), len(block)),
        )
    )


def raw_image_blocks(
    T: tuple[int, ...],
    partition: Partition,
) -> tuple[frozenset[int], ...]:
    return canonical_partition(
        {T[x] for x in block}
        for block in partition.blocks
    )


def t_star(
    T: tuple[int, ...],
    partition: Partition,
) -> tuple[frozenset[int], ...]:
    """
    Frozen arbitrary-map transport:

        T_*(Pi)

    is the equivalence relation generated by

        T(x) ~ T(y)

    whenever x and y lie in one Pi-block.
    """
    pairs: list[tuple[int, int]] = []

    for block in partition.blocks:
        images = sorted({T[x] for x in block})

        for i, left in enumerate(images):
            for right in images[i + 1 :]:
                pairs.append((left, right))

    return equivalence_classes(len(T), pairs)


def is_partition_of_x(
    n: int,
    blocks: tuple[frozenset[int], ...],
) -> bool:
    if not blocks:
        return False

    unioned: set[int] = set()

    for block in blocks:
        if not block:
            return False

        if unioned.intersection(block):
            return False

        unioned.update(block)

    return unioned == set(range(n))


def assert_equal(label: str, actual, expected) -> None:
    if actual != expected:
        raise AssertionError(
            f"{label}: actual={actual!r}, expected={expected!r}"
        )


def test_koopman_orientation() -> None:
    # Non-involution map makes transpose confusion observable.
    T = (1, 2, 2)

    K = koopman_matrix(T)

    assert_equal(
        "K row 0",
        K[0],
        (0, 1, 0),
    )

    assert_equal(
        "K row 1",
        K[1],
        (0, 0, 1),
    )

    assert_equal(
        "K row 2",
        K[2],
        (0, 0, 1),
    )

    values = (10, 20, 30)

    assert_equal(
        "Kf=f o T",
        matrix_apply(K, values),
        (20, 30, 30),
    )


def test_raw_image_family_is_not_arbitrary_map_partition() -> None:
    # X = {0,1,2}
    #
    # Pi = {{0,1},{2}}
    #
    # T(0)=0, T(1)=0, T(2)=1
    #
    # Raw image blocks:
    #     {{0},{1}}
    #
    # which does not cover X because 2 is absent.

    T = (0, 0, 1)

    partition = Partition(
        (
            frozenset({0, 1}),
            frozenset({2}),
        )
    )

    images = raw_image_blocks(T, partition)

    assert_equal(
        "raw image-block family",
        images,
        (
            frozenset({0}),
            frozenset({1}),
        ),
    )

    if is_partition_of_x(3, images):
        raise AssertionError(
            "raw image-block family was incorrectly accepted "
            "as a partition of X"
        )


def test_t_star_is_equivalence_generated() -> None:
    # Same example:
    #
    # Pi = {{0,1},{2}}
    # T = (0,0,1)
    #
    # The image identification generated by {{0,1}} is trivial
    # because T(0)=T(1)=0.
    #
    # The resulting partition of X must still contain the untouched
    # state 2 as its own equivalence class.

    T = (0, 0, 1)

    partition = Partition(
        (
            frozenset({0, 1}),
            frozenset({2}),
        )
    )

    transported = t_star(T, partition)

    assert_equal(
        "T_* transport",
        transported,
        (
            frozenset({0}),
            frozenset({1}),
            frozenset({2}),
        ),
    )

    if not is_partition_of_x(3, transported):
        raise AssertionError(
            "T_* did not produce a partition of X"
        )


def test_t_star_detects_image_identification() -> None:
    # Pi = {{0,1},{2}}
    # T = (1,1,2)
    #
    # 0 and 1 belong to the same source block and both map to 1.
    #
    # The generated relation therefore contains {1}.
    #
    # This fixture is intentionally small: the purpose is semantic
    # binding, not theorem proving.

    T = (1, 1, 2)

    partition = Partition(
        (
            frozenset({0, 1}),
            frozenset({2}),
        )
    )

    transported = t_star(T, partition)

    assert_equal(
        "T_* image-identification fixture",
        transported,
        (
            frozenset({0}),
            frozenset({1}),
            frozenset({2}),
        ),
    )


def test_permutation_image_blocks_are_partition() -> None:
    T = (1, 2, 0)

    partition = Partition(
        (
            frozenset({0, 1}),
            frozenset({2}),
        )
    )

    images = raw_image_blocks(T, partition)

    if not is_partition_of_x(3, images):
        raise AssertionError(
            "permutation image-block family was not a partition"
        )


def main() -> int:
    tests = (
        test_koopman_orientation,
        test_raw_image_family_is_not_arbitrary_map_partition,
        test_t_star_is_equivalence_generated,
        test_t_star_detects_image_identification,
        test_permutation_image_blocks_are_partition,
    )

    for test in tests:
        test()

    print("AQ-CONTRACT-001 PASS: Koopman orientation K[x,T(x)] = 1")
    print("AQ-CONTRACT-002 PASS: Kf = f o T")
    print("AQ-CONTRACT-003 PASS: raw image blocks are not assumed to partition X")
    print("AQ-CONTRACT-004 PASS: T_* uses equivalence-generated transport")
    print("AQ-CONTRACT-005 PASS: permutation image blocks preserve partition structure")
    print("AQARION OBJECT-OPERATOR CONTRACT SUITE PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
