"use strict";

/*
AQARION Quotient Structures Dashboard

This implementation computes Smith normal form for integer matrices in-browser.

The quotient is represented as:

G/H ≅ Z^q / L,

where q = freeRank + torsionInvariants.length and L is generated by:

1. torsion relations n_i e_(r+i),
2. entered subgroup-generator vectors.

The Smith diagonal entries d_i determine:

G/H ≅ Z^(q-rho) ⊕ ⊕_{d_i > 1} Z/d_i Z.

This browser implementation is intended for small and medium educational inputs.
It uses BigInt so all integer arithmetic is exact.
*/

const state = {
  mode: "cyclic",
  latestResult: null,
  generatorRows: 1,
};

const cyclicModeButton = document.getElementById("cyclicModeButton");
const generalModeButton = document.getElementById("generalModeButton");
const cyclicPanel = document.getElementById("cyclicPanel");
const generalPanel = document.getElementById("generalPanel");

const cyclicN = document.getElementById("cyclicN");
const cyclicD = document.getElementById("cyclicD");
const runCyclicButton = document.getElementById("runCyclicButton");
const loadCyclicExampleButton = document.getElementById("loadCyclicExampleButton");

const freeRankInput = document.getElementById("freeRank");
const torsionInvariantsInput = document.getElementById("torsionInvariants");
const subgroupGeneratorRows = document.getElementById("subgroupGeneratorRows");
const addGeneratorButton = document.getElementById("addGeneratorButton");
const runGeneralButton = document.getElementById("runGeneralButton");
const loadGeneralExampleButton = document.getElementById("loadGeneralExampleButton");
const basisDisplay = document.getElementById("basisDisplay");

const rankFilter = document.getElementById("rankFilter");
const torsionFilter = document.getElementById("torsionFilter");
const filterMessage = document.getElementById("filterMessage");

const structureResult = document.getElementById("structureResult");
const projectionResult = document.getElementById("projectionResult");
const identityResult = document.getElementById("identityResult");
const propertyResult = document.getElementById("propertyResult");
const projectionVisualization = document.getElementById("projectionVisualization");

const tooltip = document.getElementById("tooltip");

/* ---------- Basic exact integer helpers ---------- */

function absBigInt(value) {
  return value < 0n ? -value : value;
}

function gcdBigInt(a, b) {
  a = absBigInt(a);
  b = absBigInt(b);

  while (b !== 0n) {
    const remainder = a % b;
    a = b;
    b = remainder;
  }

  return a;
}

function lcmBigInt(a, b) {
  if (a === 0n || b === 0n) {
    return 0n;
  }

  return absBigInt((a / gcdBigInt(a, b)) * b);
}

function extendedGcd(a, b) {
  const signA = a < 0n ? -1n : 1n;
  const signB = b < 0n ? -1n : 1n;
  let oldR = absBigInt(a);
  let r = absBigInt(b);
  let oldS = 1n;
  let s = 0n;
  let oldT = 0n;
  let t = 1n;

  while (r !== 0n) {
    const quotient = oldR / r;

    [oldR, r] = [r, oldR - quotient * r];
    [oldS, s] = [s, oldS - quotient * s];
    [oldT, t] = [t, oldT - quotient * t];
  }

  return {
    g: oldR,
    x: oldS * signA,
    y: oldT * signB,
  };
}

function positiveModulo(a, n) {
  const result = a % n;
  return result < 0n ? result + n : result;
}

function cloneMatrix(matrix) {
  return matrix.map((row) => row.slice());
}

function zeroMatrix(rows, columns) {
  return Array.from(
    { length: rows },
    () => Array.from({ length: columns }, () => 0n),
  );
}

function identityMatrix(size) {
  const matrix = zeroMatrix(size, size);

  for (let i = 0; i < size; i += 1) {
    matrix[i][i] = 1n;
  }

  return matrix;
}

function matrixRankRational(inputMatrix) {
  const matrix = inputMatrix.map((row) =>
    row.map((entry) => ({
      numerator: entry,
      denominator: 1n,
    })),
  );

  const rows = matrix.length;
  const columns = rows === 0 ? 0 : matrix[0].length;
  let pivotRow = 0;
  let rank = 0;

  function normalizeFraction(value) {
    if (value.numerator === 0n) {
      return { numerator: 0n, denominator: 1n };
    }

    const divisor = gcdBigInt(value.numerator, value.denominator);
    const numerator = value.numerator / divisor;
    const denominator = value.denominator / divisor;

    return denominator < 0n
      ? { numerator: -numerator, denominator: -denominator }
      : { numerator, denominator };
  }

  function subtractFractions(left, right) {
    return normalizeFraction({
      numerator:
        left.numerator * right.denominator
        - right.numerator * left.denominator,
      denominator: left.denominator * right.denominator,
    });
  }

  function multiplyFractions(left, right) {
    return normalizeFraction({
      numerator: left.numerator * right.numerator,
      denominator: left.denominator * right.denominator,
    });
  }

  function divideFractions(left, right) {
    if (right.numerator === 0n) {
      throw new Error("Division by zero in rational rank calculation.");
    }

    return normalizeFraction({
      numerator: left.numerator * right.denominator,
      denominator: left.denominator * right.numerator,
    });
  }

  for (let column = 0; column < columns && pivotRow < rows; column += 1) {
    let candidate = pivotRow;

    while (
      candidate < rows
      && matrix[candidate][column].numerator === 0n
    ) {
      candidate += 1;
    }

    if (candidate === rows) {
      continue;
    }

    [matrix[pivotRow], matrix[candidate]] =
      [matrix[candidate], matrix[pivotRow]];

    const pivot = matrix[pivotRow][column];

    for (let j = column; j < columns; j += 1) {
      matrix[pivotRow][j] = divideFractions(matrix[pivotRow][j], pivot);
    }

    for (let row = 0; row < rows; row += 1) {
      if (row === pivotRow) {
        continue;
      }

      const coefficient = matrix[row][column];

      if (coefficient.numerator === 0n) {
        continue;
      }

      for (let j = column; j < columns; j += 1) {
        matrix[row][j] = subtractFractions(
          matrix[row][j],
          multiplyFractions(coefficient, matrix[pivotRow][j]),
        );
      }
    }

    pivotRow += 1;
    rank += 1;
  }

  return rank;
}

/* ---------- Smith normal form ---------- */

/*
This SNF routine uses exact BigInt row/column operations.

For dashboard-scale matrices, it repeatedly:
1. finds a nonzero minimum pivot in the active submatrix,
2. applies Euclidean row and column reduction,
3. clears a pivot row/column when possible,
4. restarts if the candidate pivot does not divide the remaining submatrix,
5. enforces a nonnegative pivot.

The displayed invariant factors are the nonzero diagonal entries > 1.
*/

function swapRows(matrix, first, second) {
  [matrix[first], matrix[second]] = [matrix[second], matrix[first]];
}

function swapColumns(matrix, first, second) {
  for (const row of matrix) {
    [row[first], row[second]] = [row[second], row[first]];
  }
}

function multiplyRow(matrix, rowIndex, scalar) {
  for (let column = 0; column < matrix[rowIndex].length; column += 1) {
    matrix[rowIndex][column] *= scalar;
  }
}

function multiplyColumn(matrix, columnIndex, scalar) {
  for (let row = 0; row < matrix.length; row += 1) {
    matrix[row][columnIndex] *= scalar;
  }
}

function addRowMultiple(matrix, targetRow, sourceRow, multiple) {
  for (let column = 0; column < matrix[targetRow].length; column += 1) {
    matrix[targetRow][column] += multiple * matrix[sourceRow][column];
  }
}

function addColumnMultiple(matrix, targetColumn, sourceColumn, multiple) {
  for (let row = 0; row < matrix.length; row += 1) {
    matrix[row][targetColumn] += multiple * matrix[row][sourceColumn];
  }
}

function findSmallestNonzero(matrix, start) {
  let candidate = null;

  for (let row = start; row < matrix.length; row += 1) {
    for (let column = start; column < matrix[0].length; column += 1) {
      const value = matrix[row][column];

      if (value === 0n) {
        continue;
      }

      if (
        candidate === null
        || absBigInt(value) < absBigInt(candidate.value)
      ) {
        candidate = { row, column, value };
      }
    }
  }

  return candidate;
}

function findNonDivisibleEntry(matrix, start, pivot) {
  for (let row = start; row < matrix.length; row += 1) {
    for (let column = start; column < matrix[0].length; column += 1) {
      if (matrix[row][column] % pivot !== 0n) {
        return { row, column };
      }
    }
  }

  return null;
}

function smithNormalFormDiagonal(inputMatrix) {
  if (inputMatrix.length === 0) {
    return [];
  }

  if (inputMatrix[0].length === 0) {
    return [];
  }

  const matrix = cloneMatrix(inputMatrix);
  const rows = matrix.length;
  const columns = matrix[0].length;
  const diagonal = [];

  let pivotIndex = 0;

  while (pivotIndex < rows && pivotIndex < columns) {
    let smallest = findSmallestNonzero(matrix, pivotIndex);

    if (smallest === null) {
      break;
    }

    swapRows(matrix, pivotIndex, smallest.row);
    swapColumns(matrix, pivotIndex, smallest.column);

    let stabilized = false;

    while (!stabilized) {
      stabilized = true;

      for (let row = pivotIndex + 1; row < rows; row += 1) {
        if (matrix[row][pivotIndex] === 0n) {
          continue;
        }

        const pivot = matrix[pivotIndex][pivotIndex];
        const value = matrix[row][pivotIndex];
        const quotient = value / pivot;

        addRowMultiple(matrix, row, pivotIndex, -quotient);

        if (
          absBigInt(matrix[row][pivotIndex])
          < absBigInt(matrix[pivotIndex][pivotIndex])
          && matrix[row][pivotIndex] !== 0n
        ) {
          swapRows(matrix, row, pivotIndex);
        }

        stabilized = false;
      }

      for (let column = pivotIndex + 1; column < columns; column += 1) {
        if (matrix[pivotIndex][column] === 0n) {
          continue;
        }

        const pivot = matrix[pivotIndex][pivotIndex];
        const value = matrix[pivotIndex][column];
        const quotient = value / pivot;

        addColumnMultiple(matrix, column, pivotIndex, -quotient);

        if (
          absBigInt(matrix[pivotIndex][column])
          < absBigInt(matrix[pivotIndex][pivotIndex])
          && matrix[pivotIndex][column] !== 0n
        ) {
          swapColumns(matrix, column, pivotIndex);
        }

        stabilized = false;
      }

      if (matrix[pivotIndex][pivotIndex] === 0n) {
        smallest = findSmallestNonzero(matrix, pivotIndex);

        if (smallest === null) {
          break;
        }

        swapRows(matrix, pivotIndex, smallest.row);
        swapColumns(matrix, pivotIndex, smallest.column);
        stabilized = false;
      }

      if (!stabilized) {
        continue;
      }

      const pivot = matrix[pivotIndex][pivotIndex];

      if (pivot === 0n) {
        break;
      }

      const nonDivisible = findNonDivisibleEntry(
        matrix,
        pivotIndex + 1,
        pivot,
      );

      if (nonDivisible !== null) {
        /*
        Bring a nondivisible entry into the pivot row by adding its row to
        the pivot row, then repeat Euclidean clearing. This decreases the
        effective pivot divisor until it divides the submatrix.
        */
        addRowMultiple(
          matrix,
          pivotIndex,
          nonDivisible.row,
          1n,
        );

        if (matrix[pivotIndex][pivotIndex] === 0n) {
          swapColumns(matrix, pivotIndex, nonDivisible.column);
        }

        stabilized = false;
      }
    }

    if (matrix[pivotIndex][pivotIndex] === 0n) {
      break;
    }

    if (matrix[pivotIndex][pivotIndex] < 0n) {
      multiplyRow(matrix, pivotIndex, -1n);
    }

    for (let row = pivotIndex + 1; row < rows; row += 1) {
      const pivot = matrix[pivotIndex][pivotIndex];

      if (matrix[row][pivotIndex] !== 0n) {
        const quotient = matrix[row][pivotIndex] / pivot;
        addRowMultiple(matrix, row, pivotIndex, -quotient);
      }
    }

    for (let column = pivotIndex + 1; column < columns; column += 1) {
      const pivot = matrix[pivotIndex][pivotIndex];

      if (matrix[pivotIndex][column] !== 0n) {
        const quotient = matrix[pivotIndex][column] / pivot;
        addColumnMultiple(matrix, column, pivotIndex, -quotient);
      }
    }

    diagonal.push(absBigInt(matrix[pivotIndex][pivotIndex]));
    pivotIndex += 1;
  }

  return diagonal.filter((value) => value !== 0n);
}

/* ---------- Parsing and representation ---------- */

function parseInteger(value, fieldName) {
  const text = String(value).trim();

  if (!/^-?d+$/.test(text)) {
    throw new Error(`${fieldName} must be an integer.`);
  }

  return BigInt(text);
}

function parseNonnegativeInteger(value, fieldName) {
  const parsed = parseInteger(value, fieldName);

  if (parsed < 0n) {
    throw new Error(`${fieldName} must be nonnegative.`);
  }

  return parsed;
}

function parsePositiveInteger(value, fieldName) {
  const parsed = parseInteger(value, fieldName);

  if (parsed <= 0n) {
    throw new Error(`${fieldName} must be positive.`);
  }

  return parsed;
}

function parseTorsionInvariants(text) {
  const trimmed = text.trim();

  if (trimmed === "") {
    return [];
  }

  const values = trimmed
    .split(",")
    .map((entry) => entry.trim())
    .filter((entry) => entry.length > 0)
    .map((entry, index) => {
      const value = parseInteger(entry, `Torsion invariant ${index + 1}`);

      if (value <= 1n) {
        throw new Error(
          `Torsion invariant ${index + 1} must be an integer greater than 1.`,
        );
      }

      return value;
    });

  return values;
}

function formatBigInt(value) {
  return value.toString();
}

function formatTorsionFactor(value) {
  return `ℤ/${formatBigInt(value)}ℤ`;
}

function formatGroupStructure(freeRank, torsionFactors) {
  const terms = [];

  if (freeRank === 1) {
    terms.push("ℤ");
  } else if (freeRank > 1) {
    terms.push(`ℤ^${freeRank}`);
  }

  for (const factor of torsionFactors) {
    if (factor > 1n) {
      terms.push(formatTorsionFactor(factor));
    }
  }

  return terms.length > 0 ? terms.join(" ⊕ ") : "0";
}

function formatAmbientGroup(freeRank, torsionFactors) {
  return formatGroupStructure(freeRank, torsionFactors);
}

function factorsDivideChain(factors) {
  for (let index = 0; index + 1 < factors.length; index += 1) {
    if (factors[index + 1] % factors[index] !== 0n) {
      return false;
    }
  }

  return true;
}

/* ---------- Generator row UI ---------- */

function currentCoordinateCount() {
  const freeRank = Number(parseNonnegativeInteger(
    freeRankInput.value,
    "Free rank",
  ));

  const torsion = parseTorsionInvariants(torsionInvariantsInput.value);

  return freeRank + torsion.length;
}

function coordinateNames() {
  const freeRank = Number(parseNonnegativeInteger(
    freeRankInput.value,
    "Free rank",
  ));

  const torsion = parseTorsionInvariants(torsionInvariantsInput.value);
  const names = [];

  for (let index = 0; index < freeRank; index += 1) {
    names.push(`f${index + 1}`);
  }

  for (let index = 0; index < torsion.length; index += 1) {
    names.push(`t${index + 1}`);
  }

  return names;
}

function updateBasisDisplay() {
  try {
    const names = coordinateNames();
    basisDisplay.textContent = names.length > 0
      ? names.join(", ")
      : "No ambient generators: G = 0";
  } catch (error) {
    basisDisplay.textContent = "Correct rank and torsion input to build a basis.";
  }
}

function createGeneratorRow(values = null) {
  let coordinateCount;

  try {
    coordinateCount = currentCoordinateCount();
  } catch (error) {
    showError(error.message);
    return;
  }

  if (coordinateCount === 0) {
    showError(
      "The zero group has no coordinate basis. Add free rank or torsion factors first.",
    );
    return;
  }

  state.generatorRows += 1;

  const row = document.createElement("div");
  row.className = "generator-row";
  row.dataset.generatorRow = String(state.generatorRows);

  const label = document.createElement("span");
  label.className = "generator-label";
  label.textContent = `h${state.generatorRows}`;

  const coordinates = document.createElement("div");
  coordinates.className = "coordinate-inputs";

  for (let index = 0; index < coordinateCount; index += 1) {
    const input = document.createElement("input");
    input.type = "text";
    input.inputMode = "numeric";
    input.value = values && values[index] !== undefined
      ? String(values[index])
      : "0";
    input.dataset.coordinateIndex = String(index);
    input.setAttribute("aria-label", `Generator coordinate ${index + 1}`);
    coordinates.appendChild(input);
  }

  const remove = document.createElement("button");
  remove.type = "button";
  remove.className = "remove-generator-button";
  remove.textContent = "Remove";
  remove.addEventListener("click", () => {
    row.remove();
  });

  row.append(label, coordinates, remove);
  subgroupGeneratorRows.appendChild(row);
}

function readExistingGeneratorRows() {
  const rows = [...subgroupGeneratorRows.querySelectorAll(".generator-row")];

  return rows.map((row) => {
    const inputs = [...row.querySelectorAll("input")];

    return inputs.map((input, index) =>
      parseInteger(input.value, `Subgroup coordinate ${index + 1}`),
    );
  });
}

function rebuildGeneratorRows(preserveExisting = true) {
  let oldValues = [];

  if (preserveExisting) {
    try {
      oldValues = readExistingGeneratorRows();
    } catch {
      oldValues = [];
    }
  }

  subgroupGeneratorRows.innerHTML = "";
  state.generatorRows = 0;

  if (oldValues.length === 0) {
    createGeneratorRow();
    return;
  }

  for (const values of oldValues) {
    createGeneratorRow(values);
  }
}

/* ---------- Quotient calculations ---------- */

function cyclicQuotient(n, d) {
  const reducedD = positiveModulo(d, n);
  const quotientOrder = gcdBigInt(n, reducedD);
  const subgroupOrder = n / quotientOrder;

  return {
    kind: "cyclic",
    ambient: `ℤ/${formatBigInt(n)}ℤ`,
    subgroup: `⟨${formatBigInt(reducedD)}⟩`,
    structure: quotientOrder === 1n
      ? "0"
      : `ℤ/${formatBigInt(quotientOrder)}ℤ`,
    freeRank: 0,
    torsionFactors: quotientOrder > 1n ? [quotientOrder] : [],
    finite: true,
    finiteOrder: quotientOrder,
    subgroupOrder,
    quotientOrder,
    n,
    d: reducedD,
    relationMatrix: [[n], [reducedD]],
    cyclic: true,
  };
}

function quotientFromPresentation(
  freeRank,
  torsionInvariants,
  subgroupGenerators,
) {
  const ambientDimension = freeRank + torsionInvariants.length;

  if (ambientDimension === 0) {
    return {
      kind: "general",
      ambient: "0",
      structure: "0",
      freeRank: 0,
      torsionFactors: [],
      finite: true,
      finiteOrder: 1n,
      subgroupGenerators,
      relationMatrix: [],
      diagonal: [],
      cyclic: true,
    };
  }

  const relationColumns = [];

  torsionInvariants.forEach((modulus, index) => {
    const column = Array.from(
      { length: ambientDimension },
      () => 0n,
    );

    column[freeRank + index] = modulus;
    relationColumns.push(column);
  });

  for (const generator of subgroupGenerators) {
    if (generator.length !== ambientDimension) {
      throw new Error(
        `Each subgroup generator needs ${ambientDimension} coordinates.`,
      );
    }

    relationColumns.push(generator.slice());
  }

  const relationMatrix = Array.from(
    { length: ambientDimension },
    (_, row) => relationColumns.map((column) => column[row]),
  );

  const diagonal = relationColumns.length === 0
    ? []
    : smithNormalFormDiagonal(relationMatrix);

  const relationRank = matrixRankRational(relationMatrix);
  const quotientFreeRank = ambientDimension - relationRank;
  const quotientTorsion = diagonal.filter((value) => value > 1n);

  if (!factorsDivideChain(diagonal)) {
    throw new Error(
      "Internal Smith normal form consistency check failed: "
      + "diagonal factors are not divisibility ordered.",
    );
  }

  const finite = quotientFreeRank === 0;
  const finiteOrder = finite
    ? quotientTorsion.reduce((product, value) => product * value, 1n)
    : null;

  const cyclic = (
    quotientFreeRank === 1 && quotientTorsion.length === 0
  ) || (
    quotientFreeRank === 0 && quotientTorsion.length <= 1
  ) || (
    quotientFreeRank === 0 && quotientTorsion.length === 0
  );

  return {
    kind: "general",
    ambient: formatAmbientGroup(freeRank, torsionInvariants),
    structure: formatGroupStructure(
      quotientFreeRank,
      quotientTorsion,
    ),
    freeRank: quotientFreeRank,
    torsionFactors: quotientTorsion,
    finite,
    finiteOrder,
    subgroupGenerators,
    relationMatrix,
    diagonal,
    relationRank,
    ambientDimension,
    cyclic,
    ambientFreeRank: freeRank,
    ambientTorsion: torsionInvariants,
  };
}

function runCyclicCalculation() {
  try {
    const n = parsePositiveInteger(cyclicN.value, "n");
    const d = parseInteger(cyclicD.value, "d");
    const result = cyclicQuotient(n, d);

    state.latestResult = result;
    renderResult(result);
  } catch (error) {
    showError(error.message);
  }
}

function runGeneralCalculation() {
  try {
    const freeRank = Number(parseNonnegativeInteger(
      freeRankInput.value,
      "Free rank",
    ));

    const torsionInvariants = parseTorsionInvariants(
      torsionInvariantsInput.value,
    );

    const subgroupGenerators = readExistingGeneratorRows();

    const result = quotientFromPresentation(
      freeRank,
      torsionInvariants,
      subgroupGenerators,
    );

    state.latestResult = result;
    renderResult(result);
  } catch (error) {
    showError(error.message);
  }
}

/* ---------- Rendering ---------- */

function clearResultClasses() {
  [
    structureResult,
    projectionResult,
    identityResult,
    propertyResult,
  ].forEach((element) => {
    element.className = "";
  });
}

function renderResult(result) {
  clearResultClasses();

  structureResult.className = "structure-display";
  structureResult.innerHTML = `
    <div class="structure-main">${escapeHtml(result.structure)}</div>
    <ul class="result-list">
      <li>
        <span class="result-key">Ambient group</span>
        <span class="result-value">${escapeHtml(result.ambient)}</span>
      </li>
      <li>
        <span class="result-key">Quotient type</span>
        <span class="result-value">${
          result.cyclic ? "cyclic" : "non-cyclic"
        }</span>
      </li>
      <li>
        <span class="result-key">Free rank</span>
        <span class="result-value">${result.freeRank}</span>
      </li>
      <li>
        <span class="result-key">Torsion factors</span>
        <span class="result-value">${
          result.torsionFactors.length > 0
            ? result.torsionFactors
              .map((value) => formatTorsionFactor(value))
              .join(" ⊕ ")
            : "none"
        }</span>
      </li>
      <li>
        <span class="result-key">Finite quotient</span>
        <span class="result-value">${
          result.finite ? "yes" : "no"
        }</span>
      </li>
      <li>
        <span class="result-key">Quotient order</span>
        <span class="result-value">${
          result.finite
            ? formatBigInt(result.finiteOrder)
            : "infinite"
        }</span>
      </li>
    </ul>
  `;

  projectionResult.innerHTML = `
    <ul class="result-list">
      <li>
        <span class="result-key">Canonical projection</span>
        <span class="result-value">π(g) = g + H</span>
      </li>
      <li>
        <span class="result-key">Projection type</span>
        <span class="result-value">surjective homomorphism</span>
      </li>
      <li>
        <span class="result-key">Kernel</span>
        <span class="result-value">ker(π) = H</span>
      </li>
      <li>
        <span class="result-key">First isomorphism theorem</span>
        <span class="result-value">G / ker(π) ≅ G/H</span>
      </li>
    </ul>
  `;

  identityResult.innerHTML = `
    <ul class="result-list">
      <li>
        <span class="result-key">Ambient identity</span>
        <span class="result-value">0_G</span>
      </li>
      <li>
        <span class="result-key">Identity image</span>
        <span class="result-value">π(0_G) = H</span>
      </li>
      <li>
        <span class="result-key">Quotient identity</span>
        <span class="result-value">H = 0_{G/H}</span>
      </li>
      <li>
        <span class="result-key">Addition preservation</span>
        <span class="result-value">π(g₁ + g₂) = π(g₁) + π(g₂)</span>
      </li>
    </ul>
  `;

  propertyResult.innerHTML = renderPropertyTracker(result);
  renderProjectionVisualization(result);
  applyFilters();
}

function renderPropertyTracker(result) {
  const ambientFinite = result.kind === "cyclic"
    ? true
    : result.ambientFreeRank === 0;

  const ambientTorsionOnly = result.kind === "cyclic"
    ? true
    : result.ambientFreeRank === 0;

  const rankPropagation = result.kind === "cyclic"
    ? "Ambient rank 0 → quotient rank 0"
    : `Quotient rank ${result.freeRank} ≤ ambient rank ${result.ambientFreeRank}`;

  return `
    <ul class="result-list">
      <li>
        <span class="result-key">Abelian property</span>
        <span class="result-value status-pass">propagates: yes</span>
      </li>
      <li>
        <span class="result-key">Finitely generated</span>
        <span class="result-value status-pass">propagates: yes</span>
      </li>
      <li>
        <span class="result-key">Finiteness</span>
        <span class="result-value">${
          ambientFinite
            ? "ambient finite → quotient finite"
            : result.finite
              ? "ambient infinite, quotient finite"
              : "ambient infinite → quotient remains infinite"
        }</span>
      </li>
      <li>
        <span class="result-key">Free rank</span>
        <span class="result-value">${escapeHtml(rankPropagation)}</span>
      </li>
      <li>
        <span class="result-key">Torsion behavior</span>
        <span class="result-value">${
          ambientTorsionOnly
            ? "torsion ambient → torsion quotient"
            : "torsion may appear, disappear, or change under quotient"
        }</span>
      </li>
      <li>
        <span class="result-key">Cyclicity</span>
        <span class="result-value">${
          result.cyclic
            ? "this quotient is cyclic"
            : "this quotient is non-cyclic"
        }</span>
      </li>
    </ul>
  `;
}

function renderProjectionVisualization(result) {
  if (result.kind === "cyclic") {
    const cosets = [];

    const displayCount = Number(
      result.quotientOrder > 12n ? 12n : result.quotientOrder,
    );

    for (let index = 0; index < displayCount; index += 1) {
      cosets.push(
        `<span class="coset-chip">${index} + H</span>`,
      );
    }

    if (result.quotientOrder > 12n) {
      cosets.push(
        `<span class="coset-chip more">+ ${
          formatBigInt(result.quotientOrder - 12n)
        } additional cosets</span>`,
      );
    }

    projectionVisualization.innerHTML = `
      <div class="projection-flow">
        <div class="group-visual-box">
          <h3>Ambient group</h3>
          <p class="math">ℤ/${formatBigInt(result.n)}ℤ</p>
          <p>
            Subgroup
            <span class="math">H = ⟨${formatBigInt(result.d)}⟩</span>
            has order
            <span class="math">${formatBigInt(result.subgroupOrder)}</span>.
          </p>
        </div>

        <div class="projection-arrow" aria-label="maps to">⟶</div>

        <div class="group-visual-box">
          <h3>Quotient cosets</h3>
          <p class="math">G/H ≅ ${escapeHtml(result.structure)}</p>
          <div class="coset-grid">
            ${cosets.join("")}
          </div>
        </div>
      </div>
    `;

    return;
  }

  const subgroupDisplay = result.subgroupGenerators.length === 0
    ? "H = {0}"
    : `H generated by ${result.subgroupGenerators.length} vector${
      result.subgroupGenerators.length === 1 ? "" : "s"
    }`;

  const invariantDisplay = result.torsionFactors.length > 0
    ? result.torsionFactors
      .map((factor) => formatTorsionFactor(factor))
      .join(" ⊕ ")
    : "no nontrivial torsion factors";

  projectionVisualization.innerHTML = `
    <div class="projection-flow">
      <div class="group-visual-box">
        <h3>Ambient group G</h3>
        <p class="math">${escapeHtml(result.ambient)}</p>
        <p>${escapeHtml(subgroupDisplay)}</p>
        <p>
          The relation matrix contains ambient torsion relations plus the
          entered generators of <span class="math">H</span>.
        </p>
      </div>

      <div class="projection-arrow" aria-label="maps to">⟶</div>

      <div class="group-visual-box">
        <h3>Smith-normal-form quotient</h3>
        <p class="math">G/H ≅ ${escapeHtml(result.structure)}</p>
        <p>
          Free rank:
          <span class="math">${result.freeRank}</span>
        </p>
        <p>
          Torsion:
          <span class="math">${escapeHtml(invariantDisplay)}</span>
        </p>
      </div>
    </div>
  `;
}

function resultMatchesFilters(result) {
  const rankValue = rankFilter.value;
  const torsionValue = torsionFilter.value;

  const rankMatches = (
    rankValue === "all"
    || (rankValue === "finite" && result.finite)
    || (rankValue === "positive" && result.freeRank > 0)
    || (rankValue === "zero" && result.freeRank === 0)
  );

  const hasTorsion = result.torsionFactors.length > 0;

  const torsionMatches = (
    torsionValue === "all"
    || (torsionValue === "torsion-free" && !hasTorsion)
    || (torsionValue === "has-torsion" && hasTorsion)
    || (torsionValue === "cyclic" && result.cyclic)
    || (torsionValue === "noncyclic" && !result.cyclic)
  );

  return rankMatches && torsionMatches;
}

function applyFilters() {
  const result = state.latestResult;

  if (!result) {
    filterMessage.textContent =
      "Filters apply to the most recently computed quotient.";
    return;
  }

  const matches = resultMatchesFilters(result);

  filterMessage.innerHTML = matches
    ? `<span class="status-pass">VISIBLE:</span> Current quotient matches the active rank and torsion filters.`
    : `<span class="status-warning">FILTERED:</span> Current quotient does not match the active rank and torsion filters.`;
}

function showError(message) {
  structureResult.className = "result-placeholder";
  structureResult.innerHTML = `
    <span class="status-fail">Input error:</span>
    ${escapeHtml(message)}
  `;
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

/* ---------- Mode and tooltip behavior ---------- */

function setMode(mode) {
  state.mode = mode;

  const cyclic = mode === "cyclic";

  cyclicModeButton.classList.toggle("active", cyclic);
  cyclicModeButton.setAttribute("aria-selected", String(cyclic));

  generalModeButton.classList.toggle("active", !cyclic);
  generalModeButton.setAttribute("aria-selected", String(!cyclic));

  cyclicPanel.classList.toggle("hidden", !cyclic);
  generalPanel.classList.toggle("hidden", cyclic);
}

function initializeTooltips() {
  document.querySelectorAll("[data-tooltip]").forEach((button) => {
    const show = () => {
      tooltip.textContent = button.dataset.tooltip.trim();
      tooltip.classList.remove("hidden");

      const rectangle = button.getBoundingClientRect();
      const tooltipWidth = Math.min(320, window.innerWidth - 28);

      let left = rectangle.left;
      let top = rectangle.bottom + 10;

      if (left + tooltipWidth > window.innerWidth - 14) {
        left = window.innerWidth - tooltipWidth - 14;
      }

      if (top + 150 > window.innerHeight) {
        top = Math.max(14, rectangle.top - 160);
      }

      tooltip.style.left = `${Math.max(14, left)}px`;
      tooltip.style.top = `${top}px`;
    };

    const hide = () => {
      tooltip.classList.add("hidden");
    };

    button.addEventListener("mouseenter", show);
    button.addEventListener("mouseleave", hide);
    button.addEventListener("focus", show);
    button.addEventListener("blur", hide);
  });
}

/* ---------- Event registration ---------- */

cyclicModeButton.addEventListener("click", () => setMode("cyclic"));
generalModeButton.addEventListener("click", () => setMode("general"));

runCyclicButton.addEventListener("click", runCyclicCalculation);
runGeneralButton.addEventListener("click", runGeneralCalculation);

loadCyclicExampleButton.addEventListener("click", () => {
  cyclicN.value = "12";
  cyclicD.value = "4";
  runCyclicCalculation();
});

loadGeneralExampleButton.addEventListener("click", () => {
  freeRankInput.value = "0";
  torsionInvariantsInput.value = "12,18";
  updateBasisDisplay();

  subgroupGeneratorRows.innerHTML = "";
  state.generatorRows = 0;
  createGeneratorRow([4, 6]);

  runGeneralCalculation();
});

addGeneratorButton.addEventListener("click", () => createGeneratorRow());

freeRankInput.addEventListener("change", () => {
  updateBasisDisplay();
  rebuildGeneratorRows(true);
});

torsionInvariantsInput.addEventListener("change", () => {
  updateBasisDisplay();
  rebuildGeneratorRows(true);
});

rankFilter.addEventListener("change", applyFilters);
torsionFilter.addEventListener("change", applyFilters);

/* ---------- Initialization ---------- */

updateBasisDisplay();
createGeneratorRow([4, 6]);
initializeTooltips();
runCyclicCalculation();
